In [1]:
!pip install ultralyticsplus==0.0.28 ultralytics==8.0.43


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import os
from ultralyticsplus import YOLO, render_result

# Load the model
model = YOLO('foduucom/plant-leaf-detection-and-classification')

model.overrides['conf'] = 0.1  # NMS confidence threshold
model.overrides['iou'] = 0.15  # NMS IoU threshold
model.overrides['agnostic_nms'] = False  # NMS class-agnostic
model.overrides['max_det'] = 1000  # maximum number of detections per image

# Path to the test images folder
test_images_folder = './test'  # Replace with the path to your test images folder

# Function to perform inference on an image and display the results
def perform_inference(model, image_path):
    results = model.predict(image_path)
    print(results[0].boxes)
    render = render_result(model=model, image=image_path, result=results[0])
    render.show()

for image_file in os.listdir(test_images_folder):
    if image_file.endswith(('.jpg', '.jpeg', '.png')):  # Check for valid image file extensions
        image_path = os.path.join(test_images_folder, image_file)
        perform_inference(model, image_path)

Ultralytics YOLOv8.0.43  Python-3.12.0 torch-2.5.0+cu124 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Model summary (fused): 168 layers, 11143386 parameters, 0 gradients, 28.5 GFLOPs

WARNING  NMS time limit 0.550s exceeded
image 1/1 E:\Programs\TSEC\TSEC-HACKS---artemis\mlserver\flora_detection\test\banana.jpeg: 480x640 2 bananas, 609.2ms
Speed: 32.2ms preprocess, 609.2ms inference, 929.2ms postprocess per image at shape (1, 3, 640, 640)


tensor([[  0.00000,  60.00000,  82.00000, 185.00000,   0.71247,   1.00000],
        [158.00000,  93.00000, 268.00000, 188.00000,   0.28622,   1.00000]], device='cuda:0')



image 1/1 E:\Programs\TSEC\TSEC-HACKS---artemis\mlserver\flora_detection\test\cardamom.jpeg: 448x640 1 peach, 3 cardamoms, 485.9ms
Speed: 4.1ms preprocess, 485.9ms inference, 16.9ms postprocess per image at shape (1, 3, 640, 640)


tensor([[9.10000e+01, 3.10000e+01, 1.40000e+02, 1.37000e+02, 5.95039e-01, 4.50000e+01],
        [1.32000e+02, 2.90000e+01, 1.65000e+02, 1.73000e+02, 5.61173e-01, 4.50000e+01],
        [1.99000e+02, 3.00000e+01, 2.56000e+02, 1.83000e+02, 4.27530e-01, 3.30000e+01],
        [1.85000e+02, 2.70000e+01, 2.16000e+02, 1.69000e+02, 2.53637e-01, 4.50000e+01]], device='cuda:0')



image 1/1 E:\Programs\TSEC\TSEC-HACKS---artemis\mlserver\flora_detection\test\cotton.jpeg: 448x640 2 cottons, 152.9ms
Speed: 3.5ms preprocess, 152.9ms inference, 33.9ms postprocess per image at shape (1, 3, 640, 640)


tensor([[ 14.00000,   9.00000, 181.00000, 178.00000,   0.71758,  10.00000],
        [161.00000,  42.00000, 256.00000, 146.00000,   0.48551,  10.00000]], device='cuda:0')


In [5]:
import torch

# Save the configured model
model_save_path = './saved_model.pth'
torch.save(model.model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

Model saved to ./saved_model.pth
